In [52]:
# Data Visualization

import numpy as np
import open3d as o3d

frame = []



tf_0 = np.load(r'PCD_Data/view00_tf.npy')
tf_obj = np.load(r'PCD_Data/initial_obj_pose.npy')
pcd_0 = o3d.io.read_point_cloud(r"PCD_Data/view00.pcd")


tf_0_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=50.0)
tf_0_frame.transform(tf_0)
object_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0, origin=tf_obj[:3])

frame.append(tf_0_frame)
frame.append(object_frame)

# Load the numpy file
# tf_0 = np.load(r'PCD_Data/view00_tf.npy')
# tf_1 = np.load(r'PCD_Data/view01_tf.npy')
# tf_2 = np.load(r'PCD_Data/view02_tf.npy')
# tf_3 = np.load(r'PCD_Data/view03_tf.npy')
# tf_4 = np.load(r'PCD_Data/view04_tf.npy')
# tf_5 = np.load(r'PCD_Data/view05_tf.npy')
# tf_6 = np.load(r'PCD_Data/view06_tf.npy')
# tf_7 = np.load(r'PCD_Data/view07_tf.npy')
# tf_8 = np.load(r'PCD_Data/view08_tf.npy')
# tf_obj = np.load(r'PCD_Data/initial_obj_pose.npy')

# Load pcd files
# pcd_0 = o3d.io.read_point_cloud(r"PCD_Data/view00.pcd")
# pcd_1 = o3d.io.read_point_cloud(r"PCD_Data/new_tf_down/view01.pcd")
# pcd_2 = o3d.io.read_point_cloud(r"PCD_Data/new_tf_down/view02.pcd")
# pcd_3 = o3d.io.read_point_cloud(r"PCD_Data/new_tf_down/view03.pcd")
# pcd_4 = o3d.io.read_point_cloud(r"PCD_Data/new_tf_down/view04.pcd")


# tf_0_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=50.0)
# tf_0_frame.transform(tf_0)
# tf_1_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_1_frame.transform(tf_1)
# tf_2_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_2_frame.transform(tf_2)
# tf_3_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_3_frame.transform(tf_3)
# tf_4_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_4_frame.transform(tf_4)
# tf_5_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_5_frame.transform(tf_5)
# tf_6_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_6_frame.transform(tf_6)
# tf_7_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_7_frame.transform(tf_7)
# tf_8_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
# tf_8_frame.transform(tf_8)
# frame.append(tf_0_frame)
# frame.append(tf_1_frame)
# frame.append(tf_2_frame)
# frame.append(tf_3_frame)
# frame.append(tf_4_frame)
# frame.append(tf_5_frame)
# frame.append(tf_6_frame)
# frame.append(tf_7_frame)
# frame.append(tf_8_frame)


# pasti ada
object_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0, origin=tf_obj[:3])
frame.append(object_frame)

world_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0, origin=[0, 0, 0])
frame.append(world_frame)


# test_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0, origin=[517.8511039561226, 163.59750883586588, 600.0])
# frame.append(test_frame)

o3d.visualization.draw_geometries(frame + [pcd_0])
# o3d.visualization.draw_geometries(frame + [pcd_0, pcd_1, pcd_2, pcd_3, pcd_4])



In [11]:
print(tf_obj)

print(tf_0)

[603.03202894 131.01692924   3.28730078   0.          76.25801849
   0.        ]
[[-1.98985365e-04 -9.99999969e-01 -1.47950853e-04  6.02988281e+02]
 [-9.99999888e-01  1.99048766e-04 -4.28638208e-04  1.30926978e+02]
 [ 4.28667644e-04  1.47865543e-04 -9.99999897e-01  4.77014383e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [1]:
import plotly.graph_objects as go
import numpy as np

# --- Parameters ---
SCAN_HEIGHT = 500.0
VIEWPOINTS = 8
DESIRED_ANGLE_DEG = 75.0
obj_base_pos = np.array([0, 0, 0])
scan_radius = SCAN_HEIGHT * np.tan(np.radians(90.0 - DESIRED_ANGLE_DEG))

# --- Generate Path ---
angles = np.linspace(0, 2*np.pi, VIEWPOINTS, endpoint=False)
tx = obj_base_pos[0] + scan_radius * np.cos(angles)
ty = obj_base_pos[1] + scan_radius * np.sin(angles)
tz = np.full_like(tx, obj_base_pos[2] + SCAN_HEIGHT)

# --- Plotly Visualization ---
fig = go.Figure()

# 1. Plot Viewpoints
fig.add_trace(go.Scatter3d(x=tx, y=ty, z=tz, mode='markers+lines',
                         marker=dict(size=8, color='blue'),
                         line=dict(color='blue', dash='dash'),
                         name='Camera Path'))

# 2. Plot Object Center
fig.add_trace(go.Scatter3d(x=[obj_base_pos[0]], y=[obj_base_pos[1]], z=[obj_base_pos[2]],
                         marker=dict(size=10, color='red'),
                         name='Object Center'))

# 3. Draw "Look-at" Vectors
for i in range(VIEWPOINTS):
    fig.add_trace(go.Scatter3d(x=[tx[i], obj_base_pos[0]], 
                               y=[ty[i], obj_base_pos[1]], 
                               z=[tz[i], obj_base_pos[2]],
                               mode='lines', line=dict(color='green', width=2),
                               showlegend=False))

fig.update_layout(scene=dict(aspectmode='data',
                  xaxis_title='X (mm)', yaxis_title='Y (mm)', zaxis_title='Z (mm)'),
                  title=f"Interactive Scan Path ({DESIRED_ANGLE_DEG}° Angle)")
fig.show()

In [78]:
# Helper Functions

import open3d as o3d
import numpy as np
import math
import copy
import os


def get_rotation_matrix_z(deg):
    """Creates a 3x3 rotation matrix for the Z-axis."""
    rad = math.radians(deg)
    c, s = math.cos(rad), math.sin(rad)
    return np.array([[c, -s, 0], 
                     [s,  c, 0], 
                     [0,  0, 1]])


def merge_multiview_scan(data_dir, initial_pos, initial_angle, box_size):
    """Merges multiple view PCDs and removes points below the detected plane."""
    pcd_files = sorted([f for f in os.listdir(data_dir) if f.endswith('.pcd') and "view0" in f])
    merged_pcd = o3d.geometry.PointCloud()
    
    obb = o3d.geometry.OrientedBoundingBox(
        center=np.array(initial_pos), 
        R=get_rotation_matrix_z(-initial_angle), 
        extent=np.array(box_size)
    )

    for file_name in pcd_files:
        pcd = o3d.io.read_point_cloud(os.path.join(data_dir, file_name))
   
        # 1. Detect the plane
        plane_model, inliers = pcd.segment_plane(distance_threshold=3.0, ransac_n=3, num_iterations=2000)
        [a, b, c, d] = plane_model

        # 2. Extract all points as a numpy array
        pts = np.asarray(pcd.points)

        # 3. Calculate distance to plane for every point: ax + by + cz + d
        # Points on the plane result in 0. Points above are positive, below are negative.
        distances = a * pts[:, 0] + b * pts[:, 1] + c * pts[:, 2] + d
        
        # 4. Create an index of points that are ABOVE the plane
        # A small offset (e.g., 0.5mm) to avoid keeping table noise
        above_plane_indices = np.where(distances > 0.5)[0]
        pcd = pcd.select_by_index(above_plane_indices)

        # 5. Crop to the OBB and merge
        merged_pcd += pcd.crop(obb)

    return merged_pcd


def preprocess_point_cloud(pcd, num_points):
    """Downsamples, estimates normals, and computes FPFH features."""
    pcd_down = pcd.farthest_point_down_sample(num_points)
    avg_dist = np.mean(pcd_down.compute_nearest_neighbor_distance())
    
    # Estimate Normals
    pcd_down.estimate_normals(
        o3d.geometry.KDTreeSearchParamHybrid(radius=avg_dist * 2, max_nn=30))
    
    # Orientation fix: Ensure normals point 'up' (positive Z)
    normals = np.asarray(pcd_down.normals)
    for i in range(len(normals)):
        if normals[i][2] < 0:
            normals[i] *= -1

    # Compute FPFH (Feature descriptors for global matching)
    fpfh = o3d.pipelines.registration.compute_fpfh_feature(
        pcd_down, o3d.geometry.KDTreeSearchParamHybrid(radius=avg_dist * 5, max_nn=100))
    
    return pcd_down, fpfh


def run_global_registration(source, target, source_fpfh, target_fpfh, voxel_size):
    """
    Performs RANSAC-based global registration to find a rough alignment.
    """
    distance_threshold = voxel_size * 1.5
    
    # RANSAC based on feature matching
    result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
        source, target, source_fpfh, target_fpfh, 
        mutual_filter=True,
        max_correspondence_distance=distance_threshold,
        estimation_method=o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
        ransac_n=3, 
        checkers=[
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(0.9),
            o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(distance_threshold)
        ], 
        criteria=o3d.pipelines.registration.RANSACConvergenceCriteria(4000000, 500)
    )
    return result

def run_global_registration_adaptive(source_down, target_down, source_fpfh, target_fpfh):
    """
    Performs iterative RANSAC-based global registration to find the best rough alignment.
    Matches the logic of testing multiple thresholds to find the highest fitness and lowest RMSE.
    """
    max_attempts = 5
    best_fitness = -0.1
    best_inlier_rmse = 100.0
    best_result = None
    best_threshold = None 

    # Thresholds to test, from coarse (10.0) to fine (3.0)
    thresholds = [10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0]
    # thresholds = [7]

    for attempt in range(max_attempts):
        for thr in thresholds:            
            result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
                source_down, target_down, source_fpfh, target_fpfh, 
                mutual_filter=True, # Improved matching
                max_correspondence_distance=thr,
                estimation_method=o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
                ransac_n=3, 
                checkers=[
                    o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(0.85),
                    o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(thr)
                ], 
                criteria=o3d.pipelines.registration.RANSACConvergenceCriteria(10000, 0.99)
            )

            # Update best result if fitness is good and RMSE is lower
            if result.fitness > 0.85 and result.inlier_rmse < best_inlier_rmse:
                best_fitness = result.fitness
                best_inlier_rmse = result.inlier_rmse
                best_result = result
                best_threshold = thr
            
            # Early exit if we find a very high-quality match
            if best_fitness > 0.95 and best_inlier_rmse < 2.35: 
                print(f"Excellent Global Fit Found at Threshold {best_threshold}")
                return best_result, best_threshold
            
    if best_result is None:
        print("Warning: RANSAC could not find a fit above 0.85 fitness.")
        # Fallback to the last result generated if nothing met the 0.85 criteria
        return result, thr

    print(f"RANSAC Finished. Best Threshold: {best_threshold} | Fitness: {best_fitness:.4f}")
    return best_result, best_threshold


# One time local refinement using ICP
def run_local_refinement(source, target, initial_transformation, voxel_size):
    """
    Performs ICP registration to refine the alignment found by RANSAC.
    """
    # We use a smaller threshold for ICP to ensure high precision
    distance_threshold = voxel_size * 0.4
    
    result = o3d.pipelines.registration.registration_icp(
        source, target, distance_threshold, initial_transformation,
        o3d.pipelines.registration.TransformationEstimationPointToPoint(),
        o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=2000)
    )
    return result


# Progressive Local Refinement using ICP
def run_local_refinement_adaptive(source, target, initial_trans, best_ransac_thr):
    """
    Refines alignment using an iterative ICP loop. 
    Starts with a coarse threshold and progressively tightens for precision.
    """
    # Define a range of multipliers to tighten the search radius
    # multipliers = [1.0, 0.8, 0.5, 0.25]
    multipliers = [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
    # multipliers = [0.6]
    thresholds = [best_ransac_thr * m for m in multipliers]
    
    best_result = None
    best_inlier_rmse = float('inf') # Start with the highest possible error
    
    print(f"{'Threshold':<12} | {'Fitness':<12} | {'RMSE':<12}")
    print("-" * 45)

    for thr in thresholds:
        # Execute Point-to-Point ICP
        reg_icp = o3d.pipelines.registration.registration_icp(
            source, target, thr, initial_trans,
            o3d.pipelines.registration.TransformationEstimationPointToPoint(),
            o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=1000)
        )

        # Logging the current iteration results
        print(f"{thr:<12.2f} | {reg_icp.fitness:<12.4f} | {reg_icp.inlier_rmse:<12.4f}")

        # Selection Logic: Prioritize lowest RMSE (highest precision) 
        # as long as the fitness is acceptable (e.g., > 85%)
        if reg_icp.fitness > 0.85 and reg_icp.inlier_rmse < best_inlier_rmse:
            best_inlier_rmse = reg_icp.inlier_rmse
            best_result = reg_icp

    # Fallback: if no run met the 85% fitness, return the last result
    return best_result if best_result is not None else reg_icp

In [82]:
# Main Processing Pipeline

# --- 1. Configuration ---
DATA_DIR = "PCD_Data"
SOURCE_PATH = "workpiece/z_bracket_10000.pcd" #  CAD model

tf_obj = np.load(r'PCD_Data/initial_obj_pose.npy')
YOLO_POS = tf_obj[:3]                                   # Initial guess from YOLO
YOLO_ANGLE = tf_obj[4]                                  # Initial angle from YOLO
CROP_BOX = [100, 100, 80]                               # Region of interest size


# --- 2. Data Preparation ---
print("Step 1: Merging and cleaning scans...")
source_cloud = o3d.io.read_point_cloud(SOURCE_PATH)
target_cloud = merge_multiview_scan(DATA_DIR, YOLO_POS, YOLO_ANGLE, CROP_BOX)
o3d.visualization.draw_geometries([target_cloud], window_name="Merged Target Cloud")

# Get downsampled versions and features for RANSAC
source_down, source_fpfh = preprocess_point_cloud(source_cloud, 10000)
target_down, target_fpfh = preprocess_point_cloud(target_cloud, 10000)
o3d.visualization.draw_geometries([target_down], window_name="Downsampled Target Cloud")


# --- 3. Global Alignment (RANSAC) ---
print("Step 2: Running RANSAC Global Registration...")
ransac_res, best_thr = run_global_registration_adaptive(source_down, target_down, source_fpfh, target_fpfh)
print(ransac_res)

# Visualize RANSAC result
source_temp = copy.deepcopy(source_cloud)
source_temp.transform(ransac_res.transformation)
source_temp.paint_uniform_color([1, 0, 0])
target_down.paint_uniform_color([0, 0.651, 0.929])
o3d.visualization.draw_geometries([source_temp, target_down], window_name="RANSAC Result")


Step 1: Merging and cleaning scans...
Step 2: Running RANSAC Global Registration...
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual filter, fall back to original correspondences.
[Open3D WARNING] Too few correspondences (195) after mutual 

In [83]:
# --- 4. Local Alignment (ICP) ---
print("Step 3: Running ICP Local Refinement...")
icp_res = run_local_refinement_adaptive(source_cloud, target_down, ransac_res.transformation, best_thr)
print(icp_res)

# --- 5. Extract Final Results ---
final_matrix = icp_res.transformation
initial_POS = final_matrix[:3, 3] 
initial_ORI = final_matrix[:3, :3] 
print("="*30)
print(f"Final Position: {initial_POS}")
print(f"Final Orientation Matrix:\n{initial_ORI}")
print(f"Fitness: {icp_res.fitness:.4f}")
print(f"RMSE: {icp_res.inlier_rmse:.4f}")


# --- 6. Final Visualization ---
source_final = copy.deepcopy(source_cloud).transform(final_matrix)
source_final.paint_uniform_color([1, 0, 0])         # Red: CAD Model
target_cloud.paint_uniform_color([0, 0.65, 0.93])   # Blue: Scanned Data
o3d.visualization.draw_geometries([source_final, target_cloud])

Step 3: Running ICP Local Refinement...
Threshold    | Fitness      | RMSE        
---------------------------------------------
10.00        | 1.0000       | 2.2150      
9.00         | 1.0000       | 2.2150      
8.00         | 1.0000       | 2.2150      
7.00         | 0.9997       | 2.2118      
6.00         | 0.9950       | 2.1738      
5.00         | 0.9692       | 2.0155      
4.00         | 0.9171       | 1.7837      
3.00         | 0.7607       | 1.4865      
2.00         | 0.6009       | 1.2458      
1.00         | 0.1644       | 0.7691      
RegistrationResult with fitness=9.171000e-01, inlier_rmse=1.783708e+00, and correspondence_set size of 9171
Access transformation to get result.
Final Position: [608.59589415  74.13075693  -1.38167208]
Final Orientation Matrix:
[[-1.70002780e-02 -9.99212505e-01 -3.58519206e-02]
 [ 9.99855358e-01 -1.70074392e-02 -1.05242650e-04]
 [-5.04589587e-04 -3.58485240e-02  9.99357108e-01]]
Fitness: 0.9171
RMSE: 1.7837


In [16]:
import numpy as np
import open3d as o3d
from scipy.spatial.transform import Rotation as R


def visualize_view_path(view_path):
    # 1. Create a World Coordinate Frame (Robot Base)
    # Red = X, Green = Y, Blue = Z
    world_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=100.0)
    
    geometries = [world_frame]
    
    print(f"Visualizing {len(view_path)} viewpoints...")

    for i, pose in enumerate(view_path):
        x, y, z, a, b, c = pose
        
        # 2. Convert Doosan ZYZ (a, b, c) to a 3x3 Rotation Matrix
        # Note: Doosan uses ZYZ intrinsic/extrinsic depending on setup, 
        # but 'zyz' degrees is the standard for the movel format.
        rot_matrix = R.from_euler('zyz', [a, b, c], degrees=True).as_matrix()
        
        # 3. Create 4x4 Homogeneous Matrix
        T = np.eye(4)
        T[:3, :3] = rot_matrix
        T[:3, 3] = [x, y, z]
        
        # 4. Create a coordinate frame for this viewpoint
        view_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=50.0)
        view_frame.transform(T)
        
        # Add a line to connect viewpoints to see the "circle" path
        geometries.append(view_frame)
        
        # Optional: Add a sphere at each point to make it easier to see
        sphere = o3d.geometry.TriangleMesh.create_sphere(radius=5.0)
        sphere.translate([x, y, z])
        sphere.paint_uniform_color([1, 0.7, 0]) # Golden color
        geometries.append(sphere)

        geometries.append(pcd_0)
        geometries.append(object_frame)

    # 5. Launch Visualizer
    print("Opening Open3D window...")
    o3d.visualization.draw_geometries(geometries, 
                                      window_name="Robot View Path Visualization",
                                      width=1280, height=720)



def visualize_dual_paths(camera_path, wrist_path):
    geometries = []
    
    # 1. Add World Origin (The Robot Base)
    world_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=150.0)
    geometries.append(world_frame)

    # Helper function to create frames and spheres
    def add_path_geometries(path, color, label):
        for i, pose in enumerate(path):
            x, y, z, a, b, c = pose
            
            # Create Transformation Matrix
            rot_matrix = R.from_euler('zyz', [a, b, c], degrees=True).as_matrix()
            T = np.eye(4)
            T[:3, :3] = rot_matrix
            T[:3, 3] = [x, y, z]
            
            # Create a coordinate frame (slightly smaller for clarity)
            frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=40.0)
            frame.transform(T)
            geometries.append(frame)
            
            # Create a colored sphere at the joint
            sphere = o3d.geometry.TriangleMesh.create_sphere(radius=8.0)
            sphere.translate([x, y, z])
            sphere.paint_uniform_color(color)
            geometries.append(sphere)

            geometries.append(pcd_0)
            geometries.append(object_frame)

    # 2. Add Camera Path (Green)
    add_path_geometries(camera_path, [0.0, 1.0, 0.0], "Camera")

    # 3. Add Wrist Path (Red)
    add_path_geometries(wrist_path, [1.0, 0.0, 0.0], "Wrist")

    print("Green Spheres = Camera Viewpoints")
    print("Red Spheres = Robot Wrist (Link6) Positions")
    o3d.visualization.draw_geometries(geometries, window_name="Path Comparison")

if __name__ == "__main__":
    # Your Camera Path data
    # cam_path = [[742.71, 73.13, 501.51, 180.0, 165.0, 180.0], [703.47, 167.86, 501.51, -135.99, 165.0, -135.0], [608.73, 207.11, 501.51, -90.0, 165.0, -90.0], [514.00, 167.86, 501.51, -44.0, 165.0, -44.9], [474.76, 73.13, 501.51, 0, 165.0, 0], [514.00, -21.59, 501.51, 44.0, 165.0, 44.9], [608.73, -60.83, 501.51, 90.0, 165.0, 90.0], [703.47, -21.59, 501.51, 135.99, 165.0, 135.0]]
    
    #  Wrist Path data (target link6 source realsense_RGBframe)
    # wrist_path = [[793.16, 105.63, 360.80, 89.9, 165.0, 180.0], [763.54, 177.33, 361.15, 134.0, 165.0, -135.0], [693.88, 206.70, 374.43, -180.0, 165.0, -90.0], [621.25, 177.33, 392.85, -134.0, 165.0, -44.9], [588.80, 105.63, 404.88, -90.0, 165.0, 0], [619.04, 32.83, 404.54, -45.9, 165.0, 44.9], [693.88, 2.34, 391.25, 0, 165.0, 90.0], [765.75, 32.83, 372.83, 45.9, 165.0, 135.0]]

    # #  Wrist Path data (target link6 source realsense_RGBframe inversed)
    # wrist_path = wrist_path + [[743.0615165232105, 158.21798981217492, 629.5853482672222, -90.00000000000001, 165.0000000000001, 180.0], [691.0681642602185, 273.99730996889997, 611.9126915682721, -45.99297232675505, 165.00000000709673, -135.00000002838684], [576.1835887367965, 321.08709082360303, 599.1352860195927, 0.0, 165.00000001457224, -90.0], [462.4352099491495, 273.9973094056402, 599.8124998140827, 45.99297232675505, 165.00000000709673, -44.99999997161318], [411.52048235944926, 158.21798981217495, 612.7621094403522, 90.0, 165.0000000000001, 0.0], [456.6332507599299, 39.562396513167805, 630.434766147179, 134.00702767324498, 165.00000000709673, 44.99999997161318], [576.1835887367965, -10.45394327979772, 643.2121717041553, 180.0, 165.00000001457224, 90.0], [696.8701234494381, 39.562395949907945, 642.5349579013683, -134.00702767324498, 165.00000000709682, 135.00000002838678]]

    # Wrist Path data (target realsense_RGBframe source link6)
    # wrist_path = wrist_path + [[743.1658186884355, 158.2251936387944, 629.5853307649987, -90.00000000000003, 165.00000000000006, 180.0], [691.1724657468195, 274.0045149153748, 611.9126731256426, -45.992972326755044, 165.0000000070968, -135.00000002838684], [576.2878891511538, 321.0942961877708, 599.1352668970459, -6.144359823332564e-15, 165.00000001457224, -90.0], [462.5395093517229, 274.00451435211494, 599.812480727572, 45.99297232675503, 165.0000000070968, -44.99999997161318], [411.6247811407948, 158.2251936387944, 612.7620910429224, 90.0, 165.00000000000003, 6.14435981750044e-15], [456.73754985376655, 39.56959906687835, 630.4347486901551, 134.00702767324492, 165.00000000709673, 44.99999997161313], [576.2878891511538, -10.446741299509618, 643.2121549270487, 180.0, 165.00000001457224, 90.00000000000001], [696.9744252447757, 39.569598503618444, 642.5349410882257, -134.00702767324498, 165.00000000709673, 135.0000000283868]]


    # wrist original
    # wrist_path = [[742.8705324758771, 73.26418561190337, 502.0861380713716, 180.0, 165.00000000000003, 180.0], [703.6302817510687, 167.99853110265636, 502.0861380713716, -135.99297232675505, 165.00000000709676, -135.00000002838684], [608.8959362603157, 207.23878182746472, 502.0861380713716, -90.0, 165.00000001457224, -90.0], [514.1615907695627, 167.9985311026564, 502.0861380713716, -44.00702767324496, 165.00000000709676, -44.999999971613185], [474.92134004475434, 73.26418561190339, 502.0861380713716, -5.8703522307088586e-15, 165.00000000000003, -6.0774357278757715e-15], [514.1615907695627, -21.470159878849614, 502.0861380713716, 44.007027673244956, 165.00000000709676, 44.99999997161318], [608.8959362603157, -60.71041060365798, 502.0861380713716, 90.0, 165.00000001457224, 90.0], [703.6302817510687, -21.470159878849643, 502.0861380713716, 135.99297232675502, 165.00000000709676, 135.0000000283868]]
    # cam_path = [[703.6273193359375, -21.47034454345703, 502.08209228515625, 135.99325561523438, 164.9994354248047, 134.9998016357422], [608.8892211914062, -60.709320068359375, 502.0748291015625, 90.0049057006836, 165.0000762939453, 90.00550842285156], [514.1583251953125, -21.47062110900879, 502.0827941894531, 44.00751495361328, 165.0004119873047, 45.00111389160156], [474.89642333984375, 73.24996948242188, 502.0507507324219, 0.002560675609856844, 165.00233459472656, 0.00023360311752185225], [514.1658325195312, 167.99913024902344, 502.09149169921875, 135.99429321289062, -164.9996795654297, 135.0015106201172], [608.8984375, 207.23904418945312, 502.08795166015625, 89.99959564208984, -165.00021362304688, 89.99932861328125], [703.6305541992188, 167.99734497070312, 502.0848693847656, 44.00537872314453, -165.00001525878906, 44.99803161621094], [742.8701782226562, 73.2647476196289, 502.0860595703125, 179.9998016357422, 165.00003051757812, 179.99983215332]]

    # visualize_dual_paths(cam_path, wrist_path)

    wrist_path = [[657.2088645344044, 105.78975896446484, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [617.9686138095959, 200.5241044552178, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [523.234268318843, 239.7643551800262, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [428.49992282809, 200.52410445521787, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [389.2596721032816, 105.78975896446485, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [428.49992282809, 11.055413473711852, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [523.234268318843, -28.18483725109651, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844], [617.9686138095959, 11.055413473711823, 625.0796960129207, 3.4242515563964844, -179.9999542236328, 3.4242515563964844]]
    visualize_view_path(wrist_path)

Visualizing 8 viewpoints...
Opening Open3D window...
